# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.setMinimumSize(QtCore.QSize(300, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=LoginDialog)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.titleLabel.setStyleSheet("\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"      ")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.userLineEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.userLineEdit.setStyleSheet("\n"
"        padding: 8px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 8px;\n"
"        font-size: 14px;\n"
"      ")
        self.userLineEdit.setObjectName("userLineEdit")
        self.verticalLayout.addWidget(self.userLineEdit)
        self.passLineEdit = QtWidgets.QLineEdit(parent=LoginDialog)
        self.passLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passLineEdit.setStyleSheet("\n"
"        padding: 8px;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 8px;\n"
"        font-size: 14px;\n"
"      ")
        self.passLineEdit.setObjectName("passLineEdit")
        self.verticalLayout.addWidget(self.passLineEdit)
        self.loginButton = QtWidgets.QPushButton(parent=LoginDialog)
        self.loginButton.setStyleSheet("\n"
"        padding: 10px;\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        border: none;\n"
"        border-radius: 8px;\n"
"        font-size: 14px;\n"
"      ")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.titleLabel.setText(_translate("LoginDialog", "Lab Management System"))
        self.userLineEdit.setPlaceholderText(_translate("LoginDialog", "Email Address"))
        self.passLineEdit.setPlaceholderText(_translate("LoginDialog", "Password"))
        self.loginButton.setText(_translate("LoginDialog", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec())
